# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-04 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.CharField(choices=[('PA', 'Pennsylvania'), ('IL', 'Illinois'), ('OH', 'Ohio'), ('DC', 'Washington DC'), ('ME', 'Maine')], max_length=2)),
            ],
        ),
    ]
